import FeaturedPlaylists from '@/components/Index/FeaturedPlaylists';
import Last6Playlists from '@/components/Index/Last6Playlists';
import Layout from '@/components/Layout/Layout';
import Head from 'next/head';

const Home = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout
				includeSearchInput={false}
				className='bg-[linear-gradient(rgba(88,232,128,.5)_0,#121212_100%)]'
			>
				<Last6Playlists />
				<FeaturedPlaylists />
			</Layout>
		</>
	);
};

export default Home;
