import Layout from '@/components/Layout/Layout';
import { api } from '@/utils/api';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';

const Home = () => {
	const { data: session } = useSession();

	const { data: account } = api.auth.getMe.useQuery({
		id: session?.user.id ?? '',
	});

	async function handleLogIn() {
		await signIn('spotify', {
			callbackUrl: 'http://localhost:3000/',
			redirect: true,
		});
	}

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>Test</Layout>
		</>
	);
};

export default Home;
